### ISSUE TITLE
Misses some values

### ISSUE THREAD

**Issue by vdubedout** [eymar/DrVectorAndroid#1]
Hi there thanks for the tool. 
I've tried it on an xml and it misses some line like this one
```
<path
        android:fillColor="#1b1623"
        android:pathData="M623.73,319.18a 0.6 0.6 ,0,0,1,.63-1s2,.95,3.45 0.26 a 0.6 0.6 ,0,1,1,.52,1.09c-2,.94-4.39 -0.21-4.5 -0.26Z" />
```

A friend helped me build this regexp that doesn't miss those.
search: ([^\d])\.([0-9]+)
replace: $1\0\.$2

I hope it helps

**Comment by vdubedout** [comment]
actually looks to do a better job
Search: ,\.([0-9]+)
replace: ,0\.$1

**Comment by eymar** [comment]
Hi @vdubedout 

Thank you for your contribution. Unfortunately, I haven't had path examples with commas before, so I missed such a case. All regexes I apply suppose that path uses space as a separator, therefore I added one more line to replace commas with spaces. After processing your line would look like this:
`M623.73 319.18a 0.6 0.6 0 0 1 0.63-1s2 0.95 3.45 0.26 a 0.6 0.6 0 1 1 0.52 1.09c-2 0.94-4.39 -0.21-4.5 -0.26Z`

Also, one more test case added to unit tests. 
Plugin update (v1.2.1) is already available.
