### ISSUE TITLE
Request permission to use the VectorDrawableFixinator

### ISSUE THREAD

**Issue by misakuo** [eymar/DrVectorAndroid#2]
Hello eymar,
I am the author of plugin [svgtoandroid](https://github.com/misakuo/svgtoandroid), I recently received some feedback about float declaration and the `VectorDrawableFixinator` in your project can fix it. so could you give me permission to use this class for my project?  I will keep your author information in files header and opensource it by MIT license.

**Comment by eymar** [comment]
Hello @misakuo,
Yes, you can take it.

**Comment by misakuo** [comment]
Thanks a lot!
